// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import data "bookingmgr/internal/data"
import mock "github.com/stretchr/testify/mock"

// GetBookingsModel is an autogenerated mock type for the GetBookingsModel type
type GetBookingsModel struct {
	mock.Mock
}

// Do provides a mock function with given fields: ID
func (_m *GetBookingsModel) Do(ID int) ([]*data.Booking, error) {
	ret := _m.Called(ID)

	var r0 []*data.Booking
	if rf, ok := ret.Get(0).(func(int) []*data.Booking); ok {
		r0 = rf(ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*data.Booking)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
