// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import data "bookingmgr/internal/data"
import mock "github.com/stretchr/testify/mock"

// GetCabsModel is an autogenerated mock type for the GetCabsModel type
type GetCabsModel struct {
	mock.Mock
}

// Do provides a mock function with given fields: latitude, longitude, availability
func (_m *GetCabsModel) Do(latitude int, longitude int, availability bool) ([]*data.Cab, error) {
	ret := _m.Called(latitude, longitude, availability)

	var r0 []*data.Cab
	if rf, ok := ret.Get(0).(func(int, int, bool) []*data.Cab); ok {
		r0 = rf(latitude, longitude, availability)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*data.Cab)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, int, bool) error); ok {
		r1 = rf(latitude, longitude, availability)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
